- name: First interaction
  uses: actions/first-interaction@v1.1.0
  with:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    issue-message: '# Thank you for opening this issue!\n\n We will triage this issue and get back to you as soon as possible.\n\n Thanks!'
    pr-message: 'Thanks for your pull request! We will review it and get back to you as soon as possible.'
