---
name: "pre-release"

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

jobs:
  gh_pre_release:
    runs-on: "ubuntu-latest"
   
   steps:
      - uses: "./"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
        id: "automatic_releases"

      # marvinpinto/action-keybase-notifications
      # marvinpinto/action-automatic-releases
      # marvinpinto/action-inject-ssm-secrets
      - name: "Automatically mirror release artifacts"
        env:
          GITHUB_SUPER_TOKEN: ${{ secrets.GITHUB_SUPER_TOKEN }}
        run: |
          ./scripts/mirror-actions.sh "$AUTOMATIC_RELEASES_TAG"
